apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: voucher-storage-service
  labels:
    app: voucher-storage-service
spec:
  selector:
    matchLabels:
      app: voucher-storage-service
  template:
    metadata:
      labels:
        app: voucher-storage-service
    spec:
      containers:
        - name: web
          image: docker.io/pwittchen/voucher-storage-service:latest
          ports:
            - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: voucher-storage-service
  labels:
    app: voucher-storage-service
spec:
  ports:
  - name: http
    port: 7000
  selector:
    app: voucher-storage-service
